/t2:
  ros__parameters:
    background_b: 0
    background_g: 0
    background_r: 255
    qos_overrides:
      /parameter_events:
        pulisher:
          depth: 1000
          durablity: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
    
    
